# SQL Mini Project Part 2
## By Morgan Snellgrove

In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

# Q10: 

### Produce a list of facilities with a total revenue less than 1000. The output of facility name and total revenue, sorted by revenue. Remember that there's a different cost for guests and members!

In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT costs_of_bookings.facility, ROUND(SUM(costs_of_bookings.cost),2) AS revenue
    FROM (SELECT f.name AS facility, CASE
                WHEN b.memid = 0 
                THEN f.guestcost * b.slots
                ELSE f.membercost * b.slots
                END AS cost
            FROM `Facilities` AS f 
            INNER JOIN `Bookings` AS b 
            ON f.facid = b.facid) AS costs_of_bookings
    GROUP BY costs_of_bookings.facility
    ORDER BY revenue DESC"""

    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Massage Room 1', 50351.6)
('Massage Room 2', 14454.6)
('Tennis Court 2', 14310.0)
('Tennis Court 1', 13860.0)
('Squash Court', 13468.0)
('Badminton Court', 1906.5)
('Pool Table', 270.0)
('Snooker Table', 240.0)
('Table Tennis', 180.0)

# Q11: 

### Produce a report of members and who recommended them in alphabetic surname,firstname order

In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT m1.surname||', '||m1.firstname AS member, m2.surname||', '||m2.firstname AS recommendedby 
    FROM `Members`AS m1 
    INNER JOIN `Members` AS m2 
    ON m1.memid = m2.recommendedby 
    WHERE m1.memid <> 0;
    """

    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Smith, Darren', 'Joplette, Janice')
('Smith, Darren', 'Butters, Gerald')
('Joplette, Janice', 'Dare, Nancy')
('Rownam, Tim', 'Boothe, Tim')
('Tracy, Burton', 'Stibbons, Ponder')
('Smith, Darren', 'Owen, Charles')
('Joplette, Janice', 'Jones, David')
('Stibbons, Ponder', 'Baker, Anne')
('Smith, Darren', 'Smith, Jack')
('Stibbons, Ponder', 'Bader, Florence')
('Farrell, Jemima', 'Baker, Timothy')
('Farrell, Jemima', 'Pinker, David')
('Butters, Gerald', 'Genting, Matthew')
('Smith, Darren', 'Mackenzie, Anna')
('Baker, Timothy', 'Coplin, Joan')
('Bader, Florence', 'Sarwin, Ramnaresh')
('Jones, David', 'Jones, Douglas')
('Genting, Matthew', 'Rumney, Henrietta')
('Smith, Tracy', 'Worthington-Smyth, Henry')
('Smith, Tracy', 'Purview, Millicent')
('Purview, Millicent', 'Hunt, John')
('Smith, Tracy', 'Crumpet, Erica')

# Q12: 

### Find the facilities with their usage by member, but not guests.

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT f.name AS facility, COUNT(b.slots) AS member_usage
    FROM `Bookings` AS b 
    INNER JOIN `Facilities` AS f 
    ON f.facid = b.facid
    WHERE memid <> 0
    GROUP BY f.name;
    """

    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 344)
('Massage Room 1', 421)
('Massage Room 2', 27)
('Pool Table', 783)
('Snooker Table', 421)
('Squash Court', 195)
('Table Tennis', 385)
('Tennis Court 1', 308)
('Tennis Court 2', 276)

# Q13: 

### Find the facilities usage by month, but not guests.

In [5]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT f.name AS facility, strftime('%m', b.starttime) AS month, COUNT(b.slots) AS member_usage 
    FROM `Bookings` AS b 
    INNER JOIN `Facilities` AS f 
    ON f.facid = b.facid 
    WHERE memid <> 0 
    GROUP BY f.name, strftime('%m', b.starttime) 
    ORDER BY strftime('%m', b.starttime); 
    """

    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', '07', 51)
('Massage Room 1', '07', 77)
('Massage Room 2', '07', 4)
('Pool Table', '07', 103)
('Snooker Table', '07', 68)
('Squash Court', '07', 23)
('Table Tennis', '07', 48)
('Tennis Court 1', '07', 65)
('Tennis Court 2', '07', 41)
('Badminton Court', '08', 132)
('Massage Room 1', '08', 153)
('Massage Room 2', '08', 9)
('Pool Table', '08', 272)
('Snooker Table', '08', 154)
('Squash Court', '08', 85)
('Table Tennis', '08', 143)
('Tennis Court 1', '08', 111)
('Tennis Court 2', '08', 109)
('Badminton Court', '09', 161)
('Massage Room 1', '09', 191)
('Massage Room 2', '09', 14)
('Pool Table', '09', 408)
('Snooker Table', '09', 199)
('Squash Court', '09', 87)
('Table Tennis', '09', 194)
('Tennis Court 1', '09', 132)
('Tennis Court 2', '09', 126)